In [1]:
import pandas as pd
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load the Excel file

file_path = 'E:/Python Programs/EuroAstro/total_combinations.xlsx'
data = pd.read_excel(file_path, sheet_name=None)  # Load all sheets into a dictionary

In [3]:
type(data)

dict

In [10]:
data["Sheet1"]

1st Num  2nd Num  3rd Num  4th Num  5th Num     Unnamed: 5
0             1        2        3        4        5      1 2 3 4 5
1             1        2        3        4        6      1 2 3 4 6
2             1        2        3        4        7      1 2 3 4 7
3             1        2        3        4        8      1 2 3 4 8
4             1        2        3        4        9      1 2 3 4 9
...         ...      ...      ...      ...      ...            ...
211871        1       46       47       48       49  1 46 47 48 49
211872        1       46       47       48       50  1 46 47 48 50
211873        1       46       47       49       50  1 46 47 49 50
211874        1       46       48       49       50  1 46 48 49 50
211875        1       47       48       49       50  1 47 48 49 50

[211876 rows x 6 columns]

In [11]:
# Combine data from all sheets into a single DataFrame

all_data = pd.concat(data.values())

In [12]:
all_data

1st Num  2nd Num  3rd Num  4th Num  5th Num      Unnamed: 5
0             1        2        3        4        5       1 2 3 4 5
1             1        2        3        4        6       1 2 3 4 6
2             1        2        3        4        7       1 2 3 4 7
3             1        2        3        4        8       1 2 3 4 8
4             1        2        3        4        9       1 2 3 4 9
...         ...      ...      ...      ...      ...             ...
211871       45       46       47       48       50  45 46 47 48 50
211872       45       46       47       49       50  45 46 47 49 50
211873       45       46       48       49       50  45 46 48 49 50
211874       45       47       48       49       50  45 47 48 49 50
211875       46       47       48       49       50  46 47 48 49 50

[2118760 rows x 6 columns]

In [13]:
all_data.shape

(2118760, 6)

In [15]:
all_data.drop(labels=['1st Num','2nd Num','3rd Num','4th Num','5th Num'], axis=1, inplace=True)

In [28]:
all_data.reset_index(inplace=True)

In [29]:
all_data.shape

(2118760, 2)

In [30]:
all_data["Unnamed: 5"][1]

'1 2 3 4 6'

In [31]:
# Convert string values to int One-Dimensional array

for i in range(2118760):
    all_data["Unnamed: 5"][i] = np.fromstring(all_data["Unnamed: 5"][i], sep=" ", dtype='int32')

In [34]:
all_data.drop(labels=['index'],axis=1,inplace=True)

In [35]:
all_data

Unnamed: 5
0             [1, 2, 3, 4, 5]
1             [1, 2, 3, 4, 6]
2             [1, 2, 3, 4, 7]
3             [1, 2, 3, 4, 8]
4             [1, 2, 3, 4, 9]
...                       ...
2118755  [45, 46, 47, 48, 50]
2118756  [45, 46, 47, 49, 50]
2118757  [45, 46, 48, 49, 50]
2118758  [45, 47, 48, 49, 50]
2118759  [46, 47, 48, 49, 50]

[2118760 rows x 1 columns]

In [123]:
all_data.to_hdf('E:/Python Programs/EuroAstro/total_combinations.h5',key='all_data',mode='w')

In [36]:
# Convert DataFrame to numpy array for easier manipulation

combinations = all_data.values

In [37]:
combinations

array([[array([1, 2, 3, 4, 5])],
       [array([1, 2, 3, 4, 6])],
       [array([1, 2, 3, 4, 7])],
       ...,
       [array([45, 46, 48, 49, 50])],
       [array([45, 47, 48, 49, 50])],
       [array([46, 47, 48, 49, 50])]], dtype=object)

In [38]:
# Normalize the data (optional, depending on the model's needs)

combinations = combinations / 50.0  # Since the numbers range from 1 to 50

In [39]:
combinations

array([[array([0.02, 0.04, 0.06, 0.08, 0.1 ])],
       [array([0.02, 0.04, 0.06, 0.08, 0.12])],
       [array([0.02, 0.04, 0.06, 0.08, 0.14])],
       ...,
       [array([0.9 , 0.92, 0.96, 0.98, 1.  ])],
       [array([0.9 , 0.94, 0.96, 0.98, 1.  ])],
       [array([0.92, 0.94, 0.96, 0.98, 1.  ])]], dtype=object)

In [40]:
prev_occurred = pd.read_excel("E:/Python Programs/EuroAstro/Combinations_previously_occurred.xlsx", sheet_name=None)

In [41]:
prev_occurred

{'Sheet1':      Previously_Occurred
 0          3  4 27 29 37
 1         15 19 22 46 49
 2          1  4 24 34 36
 3          1  9 23 25 40
 4         12 20 21 45 48
 ...                  ...
 1682      15 22 35 44 48
 1683        4 8 10 16 34
 1684       4 19 23 35 37
 1685       9 25 28 37 38
 1686        5 7 12 33 46
 
 [1687 rows x 1 columns]}

In [42]:
prev_occurred = prev_occurred['Sheet1']

In [43]:
prev_occurred

Previously_Occurred
0          3  4 27 29 37
1         15 19 22 46 49
2          1  4 24 34 36
3          1  9 23 25 40
4         12 20 21 45 48
...                  ...
1682      15 22 35 44 48
1683        4 8 10 16 34
1684       4 19 23 35 37
1685       9 25 28 37 38
1686        5 7 12 33 46

[1687 rows x 1 columns]

In [44]:
prev_occurred.shape

(1687, 1)

In [51]:
type(prev_occurred)

pandas.core.frame.DataFrame

In [47]:
prev_occurred.iloc[0:1,:]

Previously_Occurred
0       3  4 27 29 37

In [52]:
type(prev_occurred.iloc[0:1,:])

pandas.core.frame.DataFrame

In [53]:
prev_occurred.values

array([[' 3  4 27 29 37'],
       ['15 19 22 46 49'],
       [' 1  4 24 34 36'],
       ...,
       ['4 19 23 35 37'],
       ['9 25 28 37 38'],
       ['5 7 12 33 46']], dtype=object)

In [54]:
prev_occurred["Previously_Occurred"][0]

' 3  4 27 29 37'

In [55]:
# Convert string values to int One-Dimensional array

for i in range(1687):
    prev_occurred["Previously_Occurred"][i] = np.fromstring(prev_occurred["Previously_Occurred"][i], sep=" ", dtype='int32')

In [56]:
prev_occurred

Previously_Occurred
0       [3, 4, 27, 29, 37]
1     [15, 19, 22, 46, 49]
2       [1, 4, 24, 34, 36]
3       [1, 9, 23, 25, 40]
4     [12, 20, 21, 45, 48]
...                    ...
1682  [15, 22, 35, 44, 48]
1683    [4, 8, 10, 16, 34]
1684   [4, 19, 23, 35, 37]
1685   [9, 25, 28, 37, 38]
1686    [5, 7, 12, 33, 46]

[1687 rows x 1 columns]

In [124]:
prev_occurred.to_hdf('E:/Python Programs/EuroAstro/Previous_combinations.h5',key='prev_occurred',mode='w')

In [57]:
# Convert DataFrame to numpy array for easier manipulation

Previous_combinations = prev_occurred.values

In [58]:
Previous_combinations

array([[array([ 3,  4, 27, 29, 37])],
       [array([15, 19, 22, 46, 49])],
       [array([ 1,  4, 24, 34, 36])],
       ...,
       [array([ 4, 19, 23, 35, 37])],
       [array([ 9, 25, 28, 37, 38])],
       [array([ 5,  7, 12, 33, 46])]], dtype=object)

In [59]:
# Normalize the data (optional, depending on the model's needs)

Previous_combinations = Previous_combinations / 50.0  # Since the numbers range from 1 to 50

In [61]:
Previous_combinations

array([[array([0.06, 0.08, 0.54, 0.58, 0.74])],
       [array([0.3 , 0.38, 0.44, 0.92, 0.98])],
       [array([0.02, 0.08, 0.48, 0.68, 0.72])],
       ...,
       [array([0.08, 0.38, 0.46, 0.7 , 0.74])],
       [array([0.18, 0.5 , 0.56, 0.74, 0.76])],
       [array([0.1 , 0.14, 0.24, 0.66, 0.92])]], dtype=object)

In [64]:
len(Previous_combinations)

1687

In [94]:
X1,y1 = combinations, Previous_combinations

In [95]:
X1.shape

(2118760, 1)

In [96]:
y1.shape

(1687, 1)

In [97]:
# Flattening X 
# Now X should have shape (2118760, 5)

X = np.array([x[0] for x in X1]) 

In [98]:
X

array([[0.02, 0.04, 0.06, 0.08, 0.1 ],
       [0.02, 0.04, 0.06, 0.08, 0.12],
       [0.02, 0.04, 0.06, 0.08, 0.14],
       ...,
       [0.9 , 0.92, 0.96, 0.98, 1.  ],
       [0.9 , 0.94, 0.96, 0.98, 1.  ],
       [0.92, 0.94, 0.96, 0.98, 1.  ]])

In [99]:
# Flattening y 
# Now y should have shape (1687, 5)

y = np.array([y[0] for y in y1])

In [100]:
y

array([[0.06, 0.08, 0.54, 0.58, 0.74],
       [0.3 , 0.38, 0.44, 0.92, 0.98],
       [0.02, 0.08, 0.48, 0.68, 0.72],
       ...,
       [0.08, 0.38, 0.46, 0.7 , 0.74],
       [0.18, 0.5 , 0.56, 0.74, 0.76],
       [0.1 , 0.14, 0.24, 0.66, 0.92]])

In [101]:
# Checking the shapes

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

Shape of X: (2118760, 5)
Shape of y: (1687, 5)


In [102]:
# Creating labels for y (positive samples)

y_labels = np.ones((y.shape[0], 1))

In [103]:
y_labels

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [104]:
# Randomly sample from X to create negative samples
# Ensure negative samples are not in y by excluding indices from y

negative_sample_indices = np.random.choice(np.setdiff1d(np.arange(X.shape[0]), np.arange(y.shape[0])), y.shape[0], replace=False)
X_negative_samples = X[negative_sample_indices]
X_negative_labels = np.zeros((X_negative_samples.shape[0], 1))

In [105]:
X_negative_labels

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [106]:
# Combine the positive and negative samples for training

X_train = np.vstack((y, X_negative_samples))
y_train = np.vstack((y_labels, X_negative_labels))

In [107]:
# Shuffling the training data

shuffle_indices = np.random.permutation(X_train.shape[0])
X_train = X_train[shuffle_indices]
y_train = y_train[shuffle_indices]

In [115]:
# Building the model

model = Sequential()

model.add(Dense(256, activation='relu', input_shape=(5,)))

model.add(Dense(128, activation='relu'))

model.add(Dense(64, activation='relu'))

model.add(Dense(32, activation='relu'))

model.add(Dense(16, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))  # Sigmoid for binary classification

In [116]:
# Compiling the model

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [117]:
# Training the model

model.fit(X_train, y_train, epochs=200, batch_size=32, validation_split=0.2)

Epoch 1/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4806 - loss: 0.6947 - val_accuracy: 0.5096 - val_loss: 0.6929
Epoch 2/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4809 - loss: 0.6938 - val_accuracy: 0.4948 - val_loss: 0.6932
Epoch 3/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5143 - loss: 0.6931 - val_accuracy: 0.4993 - val_loss: 0.6931
Epoch 4/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4828 - loss: 0.6933 - val_accuracy: 0.4978 - val_loss: 0.6931
Epoch 5/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4818 - loss: 0.6932 - val_accuracy: 0.4904 - val_loss: 0.6933
Epoch 6/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4845 - loss: 0.6933 - val_accuracy: 0.4904 - val_loss: 0.6934
Epoch 7/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5013 - loss: 0.6932 - val_accuracy: 0.4904 - val_loss: 0.6933
Epoch 8/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5044 - loss: 0.6931 - val_accuracy: 0.4904 - v

In [118]:
# Predict probabilities for all combinations in X

probabilities = model.predict(X)

66212/66212 ━━━━━━━━━━━━━━━━━━━━ 41s 619us/step


In [121]:
# Getting the combination with the highest probability

next_combination_index = np.argmax(probabilities)
next_combination = X[next_combination_index]

In [122]:
# Denormalize the output to get actual lottery numbers

next_combination = np.round(next_combination * 50).astype(int)

print("Predicted next combination:", next_combination)

Predicted next combination: [ 1  2  3  4 50]
