In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import LabelEncoder, minmax_scale, MinMaxScaler, StandardScaler
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")

In [2]:
astro = pd.read_csv("E:/Python Programs/Astro_EuroMillions.csv")
astro.head()

Data      Day     Nakshatra  Pada-1  Pada-2  Pada-3  Pada-4  1st Num  \
0  Train  Tuesday       Ashwini     NaN     NaN     NaN     3.0        7   
1  Train  Tuesday       Bharani     NaN     NaN     NaN     NaN        7   
2  Train  Tuesday      Krittika     NaN     NaN     NaN     NaN        7   
3  Train  Tuesday        Rohini     NaN     NaN     NaN     NaN        7   
4  Train  Tuesday  Mrigashirsha     NaN     NaN     NaN     NaN        7   

   2nd Num  3rd Num  4th Num  5th Num  1st Lucky Star  2nd Lucky Star  
0       15       18       46       49              10              12  
1       15       18       46       49              10              12  
2       15       18       46       49              10              12  
3       15       18       46       49              10              12  
4       15       18       46       49              10              12

In [3]:
astro.fillna(value={"Pada-1":0, "Pada-2":0, "Pada-3":0, "Pada-4":0},inplace=True)

In [4]:
astro["Pada-1"] = astro["Pada-1"].astype(dtype='int32')
astro["Pada-2"] = astro["Pada-2"].astype(dtype='int32')
astro["Pada-3"] = astro["Pada-3"].astype(dtype='int32')
astro["Pada-4"] = astro["Pada-4"].astype(dtype='int32')

In [5]:
encoding = LabelEncoder()
astro["Day"] = encoding.fit_transform(astro["Day"])
astro["Nakshatra"] = encoding.fit_transform(astro["Nakshatra"])

In [6]:
astro_train = astro[astro['Data'] == 'Train']
astro_test = astro[astro['Data'] == 'Test']

In [7]:
astro_train.drop(labels='Data', axis=1, inplace=True)

In [8]:
astro_test.drop(labels='Data', axis=1, inplace=True)

In [10]:
astro_train.head()

Day  Nakshatra  Pada-1  Pada-2  Pada-3  Pada-4  1st Num  2nd Num  3rd Num  \
0    1          3       0       0       0       3        7       15       18   
1    1          4       0       0       0       0        7       15       18   
2    1          9       0       0       0       0        7       15       18   
3    1         19       0       0       0       0        7       15       18   
4    1         11       0       0       0       0        7       15       18   

   4th Num  5th Num  1st Lucky Star  2nd Lucky Star  
0       46       49              10              12  
1       46       49              10              12  
2       46       49              10              12  
3       46       49              10              12  
4       46       49              10              12

In [12]:
astro_test.reset_index(inplace=True, drop=True)

In [13]:
astro_test.head()

Day  Nakshatra  Pada-1  Pada-2  Pada-3  Pada-4  1st Num  2nd Num  3rd Num  \
0    0          3       0       0       0       6        6        9       10   
1    0          4       0       1       0       0        6        9       10   
2    0          9       0       3       0       0        6        9       10   
3    0         19       0       0       0       0        6        9       10   
4    0         11       0       0       0       0        6        9       10   

   4th Num  5th Num  1st Lucky Star  2nd Lucky Star  
0       30       49               3               4  
1       30       49               3               4  
2       30       49               3               4  
3       30       49               3               4  
4       30       49               3               4

In [16]:
scaler = StandardScaler().fit(astro_train.values)
astro_train_transformed = scaler.transform(astro_train.values)
astro_train_scaled = pd.DataFrame(data=astro_train_transformed, index=astro_train.index)

In [17]:
astro_train_scaled.head()

0         1         2         3         4         5         6   \
0  0.973438 -1.299849 -0.253278 -0.270101 -0.240524  1.471163 -0.405312   
1  0.973438 -1.170852 -0.253278 -0.270101 -0.240524 -0.285504 -0.405312   
2  0.973438 -0.525869 -0.253278 -0.270101 -0.240524 -0.285504 -0.405312   
3  0.973438  0.764099 -0.253278 -0.270101 -0.240524 -0.285504 -0.405312   
4  0.973438 -0.267875 -0.253278 -0.270101 -0.240524 -0.285504 -0.405312   

         7         8         9         10        11        12  
0 -0.163685 -0.642017  1.439382  0.856244  2.090883  1.146773  
1 -0.163685 -0.642017  1.439382  0.856244  2.090883  1.146773  
2 -0.163685 -0.642017  1.439382  0.856244  2.090883  1.146773  
3 -0.163685 -0.642017  1.439382  0.856244  2.090883  1.146773  
4 -0.163685 -0.642017  1.439382  0.856244  2.090883  1.146773

In [18]:
scaler = StandardScaler().fit(astro_test.values)
astro_test_transformed = scaler.transform(astro_test.values)
astro_test_scaled = pd.DataFrame(data=astro_test_transformed, index=astro_test.index)

In [19]:
astro_test_scaled.head()

0         1         2         3         4         5        6   \
0 -0.950014 -1.289071 -0.264237 -0.303522 -0.257065  4.021985 -0.48962   
1 -0.950014 -1.159649 -0.264237  0.244272 -0.257065 -0.227102 -0.48962   
2 -0.950014 -0.512534 -0.264237  1.339860 -0.257065 -0.227102 -0.48962   
3 -0.950014  0.781694 -0.264237 -0.303522 -0.257065 -0.227102 -0.48962   
4 -0.950014 -0.253688 -0.264237 -0.303522 -0.257065 -0.227102 -0.48962   

         7         8         9         10        11        12  
0 -0.687194 -1.335704 -0.163256  0.934328 -0.397295 -1.678523  
1 -0.687194 -1.335704 -0.163256  0.934328 -0.397295 -1.678523  
2 -0.687194 -1.335704 -0.163256  0.934328 -0.397295 -1.678523  
3 -0.687194 -1.335704 -0.163256  0.934328 -0.397295 -1.678523  
4 -0.687194 -1.335704 -0.163256  0.934328 -0.397295 -1.678523

In [26]:
X = astro_train_scaled.loc[:,0:5]
y1 = astro_train_scaled.loc[:,6:6]
y2 = astro_train_scaled.loc[:,7:7]
y3 = astro_train_scaled.loc[:,8:8]
y4 = astro_train_scaled.loc[:,9:9]
y5 = astro_train_scaled.loc[:,10:10]
y6 = astro_train_scaled.loc[:,11:11]
y7 = astro_train_scaled.loc[:,12:12]

In [27]:
Xt = astro_test_scaled.loc[:,0:5]
yt1 = astro_test_scaled.loc[:,6:6]
yt2 = astro_test_scaled.loc[:,7:7]
yt3 = astro_test_scaled.loc[:,8:8]
yt4 = astro_test_scaled.loc[:,9:9]
yt5 = astro_test_scaled.loc[:,10:10]
yt6 = astro_test_scaled.loc[:,11:11]
yt7 = astro_test_scaled.loc[:,12:12]

In [35]:
model = LinearRegression()
model.fit(X,y1)

LinearRegression()

In [36]:
w, b = model.coef_, model.intercept_
w, b

(array([[-0.12701009, -0.00910691,  0.02651757,  0.05549366, -0.0098504 ,
         -0.07083263]]),
 array([7.23146724e-18]))

In [40]:
yt1.values

array([[-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [-0.48962018],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3.27250409],
       [ 3

In [39]:
y_predict = model.predict(Xt)
y_predict

array([[-0.17380518],
       [ 0.15638927],
       [ 0.21129424],
       [ 0.10831054],
       [ 0.11773968],
       [ 0.12952611],
       [ 0.1153824 ],
       [ 0.11066783],
       [ 0.12834746],
       [ 0.11891832],
       [ 0.11184647],
       [ 0.10123869],
       [-0.22868208],
       [ 0.12481154],
       [ 0.10477461],
       [ 0.10006004],
       [ 0.13070475],
       [ 0.12127561],
       [ 0.11656104],
       [ 0.11420375],
       [ 0.10359597],
       [ 0.10595326],
       [ 0.12363289],
       [ 0.1071319 ],
       [ 0.15129087],
       [ 0.26608816],
       [ 0.37600915],
       [ 0.19931259],
       [-0.12718541],
       [-0.00293091],
       [-0.04305999],
       [-0.14604369],
       [-0.13661455],
       [-0.12482812],
       [-0.13897183],
       [-0.1436864 ],
       [-0.12600676],
       [-0.1354359 ],
       [-0.14250776],
       [-0.15311554],
       [-0.48303631],
       [-0.12954269],
       [-0.14957961],
       [-0.15429418],
       [-0.12364948],
       [-0

In [41]:
model.score(Xt, yt1)

-0.05170736274376164