In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from sklearn.model_selection import train_test_split
from sklearn.metrics import ConfusionMatrixDisplay, accuracy_score
from sklearn.preprocessing import LabelEncoder, minmax_scale, MinMaxScaler, StandardScaler, OneHotEncoder, RobustScaler

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("E:/Python Programs/EuroAstro/test_y1.csv")
df.head()

X                 y
0   20 40 9 2 80 84 72 84 5 54  16 28 32 44 48 1
1  30 60 26 2 42 84 19 84 5 54  12 34 37 38 42 1
2  40 80 48 3 63 22 38 84 5 54  18 23 37 41 42 4
3  11 21 80 3 22 22 76 84 5 54   2 10 18 34 35 6
4  11 42 92 4 66 22 20 84 5 54   4 10 27 38 40 3

In [3]:
df.shape

(375, 2)

In [4]:
# converting entire column of X into int 2 Dimensional

df.X = df.X.apply(lambda x: np.array(x.split(), dtype='int32').reshape(5,2))
df.head()

X                 y
0   [[20, 40], [9, 2], [80, 84], [72, 84], [5, 54]]  16 28 32 44 48 1
1  [[30, 60], [26, 2], [42, 84], [19, 84], [5, 54]]  12 34 37 38 42 1
2  [[40, 80], [48, 3], [63, 22], [38, 84], [5, 54]]  18 23 37 41 42 4
3  [[11, 21], [80, 3], [22, 22], [76, 84], [5, 54]]   2 10 18 34 35 6
4  [[11, 42], [92, 4], [66, 22], [20, 84], [5, 54]]   4 10 27 38 40 3

In [5]:
# converting entire column of y into int 1 Dimensional

df.y = df.y.apply(lambda x: np.array(x.split(), dtype='int32').reshape(6,))
df.head()

X                        y
0   [[20, 40], [9, 2], [80, 84], [72, 84], [5, 54]]  [16, 28, 32, 44, 48, 1]
1  [[30, 60], [26, 2], [42, 84], [19, 84], [5, 54]]  [12, 34, 37, 38, 42, 1]
2  [[40, 80], [48, 3], [63, 22], [38, 84], [5, 54]]  [18, 23, 37, 41, 42, 4]
3  [[11, 21], [80, 3], [22, 22], [76, 84], [5, 54]]   [2, 10, 18, 34, 35, 6]
4  [[11, 42], [92, 4], [66, 22], [20, 84], [5, 54]]   [4, 10, 27, 38, 40, 3]

In [6]:
X = np.zeros((375,5,2))
X

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       ...,

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [7]:
# Now assigning X data to the zeros array using a loop in order to prepare our X.

for i in range(375):
    X[i] = df.X[i]

In [8]:
X

array([[[ 20.,  40.],
        [  9.,   2.],
        [ 80.,  84.],
        [ 72.,  84.],
        [  5.,  54.]],

       [[ 30.,  60.],
        [ 26.,   2.],
        [ 42.,  84.],
        [ 19.,  84.],
        [  5.,  54.]],

       [[ 40.,  80.],
        [ 48.,   3.],
        [ 63.,  22.],
        [ 38.,  84.],
        [  5.,  54.]],

       ...,

       [[ 80.,  24.],
        [ 54.,  12.],
        [ 20.,  12.],
        [ 27.,  50.],
        [104.,  26.]],

       [[ 42.,  32.],
        [ 12.,   4.],
        [ 30.,  12.],
        [ 36.,  50.],
        [104.,  26.]],

       [[ 63.,   9.],
        [ 21.,   8.],
        [ 30.,  16.],
        [ 10.,  50.],
        [104.,  26.]]])

In [21]:
y = np.zeros((375,6))
y.shape

(375, 6)

In [22]:
for i in range(375):
    y[i] = df.y[i]

In [23]:
y

array([[16., 28., 32., 44., 48.,  1.],
       [12., 34., 37., 38., 42.,  1.],
       [18., 23., 37., 41., 42.,  4.],
       ...,
       [ 4., 19., 23., 35., 37.,  4.],
       [ 9., 25., 28., 37., 38.,  2.],
       [ 5.,  7., 12., 33., 46.,  3.]])

In [24]:
y.shape

(375, 6)

In [29]:
model = Sequential()
model.add(Flatten(input_shape=(5,2)))

model.add(Dense(200))
model.add(Activation('relu'))

model.add(Dense(400))
model.add(Activation('relu'))

model.add(Dense(800))
model.add(Activation('relu'))

model.add(Dense(6))
model.add(Activation('softmax'))

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten_2 (Flatten)                  │ (None, 10)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 200)                 │           2,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_8 (Activation)            │ (None, 200)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 400)                 │          80,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_9 (Activation)            │ (None, 400)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 800)                 │         320,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_10 (Activation)           │ (None, 800)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 6)                   │           4,806 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_11 (Activation)           │ (None, 6)                   │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 408,206 (1.56 MB)

 Trainable params: 408,206 (1.56 MB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((300, 5, 2), (75, 5, 2), (300, 6), (75, 6))

In [31]:
model.fit(X_train, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.6259 - loss: 1861.1213 - val_accuracy: 1.0000 - val_loss: 7687.1382
Epoch 2/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 12404.4912 - val_accuracy: 1.0000 - val_loss: 32134.5176
Epoch 3/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 45853.6719 - val_accuracy: 1.0000 - val_loss: 96019.5078
Epoch 4/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 131164.0000 - val_accuracy: 1.0000 - val_loss: 236779.5312
Epoch 5/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 310723.7812 - val_accuracy: 1.0000 - val_loss: 514503.7188
Epoch 6/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 648495.5625 - val_accuracy: 1.0000 - val_loss: 1018722.5625
Epoch 7/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1287840.6250 - val_accuracy: 1.0000 - val_loss: 1870305.1250
Epoch 8/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy

In [32]:
model.evaluate(X_test,y_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 47645577216.0000 


[47528566784.0, 1.0]

In [33]:
y_predict = model.predict(X_test)
y_predict

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0.