In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import (train_test_split, KFold, LeaveOneOut, LeavePOut, RepeatedKFold, RepeatedStratifiedKFold,
                                     StratifiedKFold)
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import balanced_accuracy_score, precision_score, recall_score, accuracy_score

In [2]:
fruits=pd.read_csv("E:/Python Programs/fruits.csv")
X = fruits[["sphericity", "weight"]]
y = fruits["label"]

In [3]:
kf1 = KFold(n_splits=5, shuffle=False)
kf1.split(X)

<generator object _BaseKFold.split at 0x0000027E70B3DB40>

In [4]:
for ix_train, ix_test in kf1.split(X):
    print(ix_train)
    print(ix_test)
    print()

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

[ 0  1  2  3  4  5  6  7  8  9 10 11 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[12 13 14 15 16 17 18 19 20 21 22 23]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[24 25 26 27 28 29 30 31 32 33 34 35]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 48 49 50 51 52 53 54 55 56 57 58 59]
[36 37 38 39 40 41 42 43 44 45 46 47]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
[48 49 50 51 52 53 54 55 56 57 58 59]



In [5]:
kf2 = KFold(n_splits=5, shuffle=True)
kf2.split(X)

<generator object _BaseKFold.split at 0x0000027E70B3EB00>

In [6]:
for ix_train, ix_test in kf2.split(X):
    print(ix_train)
    print(ix_test)
    print()

[ 0  1  2  4  5  6  7  8  9 10 12 13 14 16 17 18 19 20 21 22 23 24 25 26
 29 31 32 34 35 36 38 39 40 41 42 43 45 46 47 48 49 50 51 53 55 57 58 59]
[ 3 11 15 27 28 30 33 37 44 52 54 56]

[ 0  1  2  3  5  6  8 10 11 12 13 14 15 16 17 18 19 22 24 26 27 28 29 30
 31 32 33 35 36 37 39 41 42 44 45 47 48 49 50 51 52 53 54 55 56 57 58 59]
[ 4  7  9 20 21 23 25 34 38 40 43 46]

[ 0  1  3  4  5  6  7  8  9 11 13 14 15 16 18 20 21 22 23 25 27 28 29 30
 33 34 36 37 38 39 40 41 42 43 44 45 46 47 48 51 52 53 54 55 56 57 58 59]
[ 2 10 12 17 19 24 26 31 32 35 49 50]

[ 2  3  4  5  7  9 10 11 12 14 15 16 17 19 20 21 23 24 25 26 27 28 30 31
 32 33 34 35 36 37 38 39 40 41 43 44 46 47 49 50 52 53 54 55 56 57 58 59]
[ 0  1  6  8 13 18 22 29 42 45 48 51]

[ 0  1  2  3  4  6  7  8  9 10 11 12 13 15 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 37 38 40 42 43 44 45 46 48 49 50 51 52 54 56]
[ 5 14 16 36 39 41 47 53 55 57 58 59]



In [7]:
model = DecisionTreeClassifier(criterion='entropy')
accuracy = []
for ix_train, ix_test in kf2.split(X):
    X_train = X.iloc[ix_train]
    X_test = X.iloc[ix_test]
    y_train = y.iloc[ix_train]
    y_test = y.iloc[ix_test]
    model.fit(X_train, y_train)
    accuracy.append(model.score(X_test, y_test))
print(accuracy)

[1.0, 1.0, 1.0, 1.0, 0.9166666666666666]


In [8]:
np.mean(accuracy)

0.9833333333333334

In [9]:
loo = LeaveOneOut()
for ix_train, ix_test in loo.split(X):
    print(ix_train)
    print(ix_test)
    print()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]
[0]

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]
[1]

[ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]
[2]

[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]
[3]

[ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59]
[4]

[ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [10]:
loo = LeaveOneOut()
dt_model = DecisionTreeClassifier(criterion='entropy')
accuracy = []
for ix_train, ix_test in loo.split(X):
    X_train, X_test, y_train, y_test = X.iloc[ix_train], X.iloc[ix_test], y.iloc[ix_train], y.iloc[ix_test]
    dt_model.fit(X_train, y_train)
    dt_y_predict = dt_model.predict(X_test)
    accuracy.append(dt_model.score(X_test, y_test))
print(accuracy)
print(np.mean(accuracy))

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
0.9666666666666667


In [11]:
knn_model = KNeighborsClassifier()
accuracy = []
for ix_train, ix_test in loo.split(X):
    X_train, X_test, y_train, y_test = X.iloc[ix_train], X.iloc[ix_test], y.iloc[ix_train], y.iloc[ix_test]
    knn_model.fit(X_train, y_train)
    knn_y_predict = knn_model.predict(X_test)
    accuracy.append(knn_model.score(X_test, y_test))
print(accuracy)
print(np.mean(accuracy))

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0]
0.95
