In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import math as m
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut, LeavePOut, RepeatedKFold, ShuffleSplit
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import balanced_accuracy_score, precision_score, recall_score, accuracy_score

In [2]:
fruits=pd.read_csv("E:/Python Programs/fruits.csv")
X = fruits[["sphericity", "weight"]]
y = fruits["label"]

In [4]:
# lpo = LeavePOut(p=3)
# model = DecisionTreeClassifier(criterion='entropy')
# accuracy = []
# start_time = datetime.now()
# for ix_train, ix_test in lpo.split(X):
#    X_train, X_test, y_train, y_test = X.iloc[ix_train], X.iloc[ix_test], y.iloc[ix_train], y.iloc[ix_test]
#    model.fit(X_train, y_train)
#    accuracy.append(model.score(X_test, y_test))
# end_time = datetime.now()
# print("Time taken to execute: ", end_time - start_time)
# print(accuracy)

Time taken to execute:  0:01:25.506042
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6666666666666666, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6666666666666666, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6666666666666666, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6666666666666666, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6666666666666666, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.6666666666666666, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 

In [7]:
m.comb(60,3)

34220

In [8]:
len(accuracy)

34220

In [9]:
# Out of 60 fruits, making 1770 combinations of 2 fruits for testing i.e., 60-C-2 ==> 1770 

lpo = LeavePOut(p=2)
model = DecisionTreeClassifier(criterion='entropy')
accuracy = []
start_time = datetime.now()
for ix_train, ix_test in lpo.split(X):
    X_train, X_test, y_train, y_test = X.iloc[ix_train], X.iloc[ix_test], y.iloc[ix_train], y.iloc[ix_test]
    model.fit(X_train, y_train)
    accuracy.append(model.score(X_test, y_test))
end_time = datetime.now()
print("Time taken to execute: ", end_time - start_time)
print(accuracy)

Time taken to execute:  0:00:04.526742
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 

In [29]:
for ix_train, ix_test in lpo.split(X):
    print(ix_test)

[0 1]
[0 2]
[0 3]
[0 4]
[0 5]
[0 6]
[0 7]
[0 8]
[0 9]
[ 0 10]
[ 0 11]
[ 0 12]
[ 0 13]
[ 0 14]
[ 0 15]
[ 0 16]
[ 0 17]
[ 0 18]
[ 0 19]
[ 0 20]
[ 0 21]
[ 0 22]
[ 0 23]
[ 0 24]
[ 0 25]
[ 0 26]
[ 0 27]
[ 0 28]
[ 0 29]
[ 0 30]
[ 0 31]
[ 0 32]
[ 0 33]
[ 0 34]
[ 0 35]
[ 0 36]
[ 0 37]
[ 0 38]
[ 0 39]
[ 0 40]
[ 0 41]
[ 0 42]
[ 0 43]
[ 0 44]
[ 0 45]
[ 0 46]
[ 0 47]
[ 0 48]
[ 0 49]
[ 0 50]
[ 0 51]
[ 0 52]
[ 0 53]
[ 0 54]
[ 0 55]
[ 0 56]
[ 0 57]
[ 0 58]
[ 0 59]
[1 2]
[1 3]
[1 4]
[1 5]
[1 6]
[1 7]
[1 8]
[1 9]
[ 1 10]
[ 1 11]
[ 1 12]
[ 1 13]
[ 1 14]
[ 1 15]
[ 1 16]
[ 1 17]
[ 1 18]
[ 1 19]
[ 1 20]
[ 1 21]
[ 1 22]
[ 1 23]
[ 1 24]
[ 1 25]
[ 1 26]
[ 1 27]
[ 1 28]
[ 1 29]
[ 1 30]
[ 1 31]
[ 1 32]
[ 1 33]
[ 1 34]
[ 1 35]
[ 1 36]
[ 1 37]
[ 1 38]
[ 1 39]
[ 1 40]
[ 1 41]
[ 1 42]
[ 1 43]
[ 1 44]
[ 1 45]
[ 1 46]
[ 1 47]
[ 1 48]
[ 1 49]
[ 1 50]
[ 1 51]
[ 1 52]
[ 1 53]
[ 1 54]
[ 1 55]
[ 1 56]
[ 1 57]
[ 1 58]
[ 1 59]
[2 3]
[2 4]
[2 5]
[2 6]
[2 7]
[2 8]
[2 9]
[ 2 10]
[ 2 11]
[ 2 12]
[ 2 13]
[ 2 14]
[ 2 15]
[ 2 16]


In [10]:
m.comb(60,2), len(accuracy)

(1770, 1770)

In [12]:
# 4 (n_splits=4) samples repeated for 5 (n_repeats=5) times

rkf = RepeatedKFold(n_splits=4, n_repeats=5)
model = DecisionTreeClassifier(criterion='entropy')
accuracy = []
start_time = datetime.now()
for ix_train, ix_test in rkf.split(X):
    X_train, X_test, y_train, y_test = X.iloc[ix_train], X.iloc[ix_test], y.iloc[ix_train], y.iloc[ix_test]
    model.fit(X_train, y_train)
    accuracy.append(model.score(X_test, y_test))
end_time = datetime.now()
print("Time taken to execute: ", end_time - start_time)
print(accuracy)

Time taken to execute:  0:00:00.061644
[0.8, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.8666666666666667, 0.8666666666666667, 1.0, 0.9333333333333333, 1.0, 1.0, 1.0, 0.9333333333333333, 1.0, 1.0, 0.9333333333333333, 0.9333333333333333]


In [13]:
len(accuracy)

20

In [21]:
# taking 5 samples 5 times

spf = ShuffleSplit(n_splits=5)
model = DecisionTreeClassifier(criterion='entropy')
accuracy = []
start_time = datetime.now()
for ix_train, ix_test in spf.split(X):
    X_train, X_test, y_train, y_test = X.iloc[ix_train], X.iloc[ix_test], y.iloc[ix_train], y.iloc[ix_test]
    model.fit(X_train, y_train)
    accuracy.append(model.score(X_test, y_test))
end_time = datetime.now()
print("Time taken to execute: ", end_time - start_time)
print(accuracy)

Time taken to execute:  0:00:00.015093
[1.0, 1.0, 1.0, 1.0, 1.0]


In [22]:
len(accuracy)

5

In [23]:
for ix_train, ix_test in spf.split(X):
    print("Training Indexes")
    print(ix_train)
    print("Testing Indexes")
    print(ix_test)
    print()

Training Indexes
[23  1 12 52 16 44 18 21 51 57 40 25 42 53 47 10 15  6 34 14 17 24 50  0
 13 27 46 55 33 41 59  2 26 43 35  9  4 11 30  5 48  8 22 45 37 29 38  3
 32 58  7 49 54 20]
Testing Indexes
[56 36 28 19 39 31]

Training Indexes
[36  9 14 56 24 53 46 57 27 20 18 17 38 10 40 52  1  5 26  0 19 51 30  7
 29 25 49 11 12 28 23 35 44  4 47 15  6 41 42 16 39 31 33 22 45 32 50  3
 34  2 21 43  8 37]
Testing Indexes
[58 48 59 55 54 13]

Training Indexes
[30 22 33 36  2 34  8  7  6 47  9 26 41 27 37 10 56 24 29 25 11 20 38  0
 46 51 53 48 21 55 44 35 31 23 16 49 50 57 45 18 32  1 59 43 52 28 13 14
 40  3 17  4  5 12]
Testing Indexes
[58 15 19 42 54 39]

Training Indexes
[ 5 17  9 54 14 48 30 41 10 34 53 32 51  4 52 39 38 44 12  8  0  2 37 26
 59 49 19  3 29 55 40 25  6 21 57 24 22 15 47 42 23 16 27 35  1 18 13 11
  7 20 58 56 33 43]
Testing Indexes
[36 31 28 45 46 50]

Training Indexes
[54 19  7 27 18 48 17 58 43 44  8 40 46 51 33 52  1 11  6  0 47 36 21  5
 12 41 28 14  9 49 22 23 16 45

In [26]:
# taking random 20 samples (test_size=20) and repeat it 5 times (n_splits=5)

spf_1 = ShuffleSplit(n_splits=5, test_size=20)
model = DecisionTreeClassifier(criterion='entropy')
accuracy = []
start_time = datetime.now()
for ix_train, ix_test in spf_1.split(X):
    X_train, X_test, y_train, y_test = X.iloc[ix_train], X.iloc[ix_test], y.iloc[ix_train], y.iloc[ix_test]
    model.fit(X_train, y_train)
    accuracy.append(model.score(X_test, y_test))
end_time = datetime.now()
print("Time taken to execute: ", end_time - start_time)
print(accuracy)
len(accuracy)

Time taken to execute:  0:00:00.015018
[0.9, 0.9, 0.95, 0.9, 0.95]


5

In [28]:
for ix_train, ix_test in spf_1.split(X):
    print("Training Indexes")
    print(ix_train)
    print("Testing Indexes")
    print(ix_test)
    print()

Training Indexes
[45 51 39  9 40 57 35 19 50  2  0 59 27 31 25 53 36 34 43 54 14 11 52 21
 58  3  5 15 22 16 28 32 55 26 13 20 56 33 30 41]
Testing Indexes
[38 12  1 37 10 48  6 42  8 49 24 44 18 29 47  7  4 17 46 23]

Training Indexes
[34  5 25 51 36 29 53  8 57 46 33 16  7  1 37 56 12 47 31 45 24  6 30 59
 27 21 35 44 43 10  2 17 49 14 11  9  0 38 42 22]
Testing Indexes
[19 58 41 55 23 48 54 26 15 28 18 32 50 39 13  3 40 20  4 52]

Training Indexes
[40 52 18 24  4 47 36 58 13 33 35 57 27 25 20 46 56 42 34  3 10 11 38 16
 51 55  7 22 21 39 31 43 28 30  9  2 26 14 53  0]
Testing Indexes
[23 41 49  8 19 15 17  6 29 44 50  5 37 12 45 54 48 32 59  1]

Training Indexes
[38 50 12 22  8  3 45 33 37  9 24  2  7 56 16 43 14 23 11 36 10 29 44 51
 19  4 25  1 15 21 42 26 46  0 54 53 28 20 52 35]
Testing Indexes
[41 17  5 27 40 39 55 48 59 18 13  6 58 32 30 31 47 49 57 34]

Training Indexes
[53 24  9 59 32 30 21 44  8 47 16  0  6 25 29 50 33 36 42 38 10 49 55 56
 15 43 58 12 51  2 57  3 54 48 37 