In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [3]:
a = np.array([19,2,8,9,22,22,13,17,14,15,22])
a

array([19,  2,  8,  9, 22, 22, 13, 17, 14, 15, 22])

##### find/extract the elements 19 and 22 in an numpy array

In [4]:
# Boolean array

np.logical_or(a==19,a==22)

array([ True, False, False, False,  True,  True, False, False, False,
       False,  True])

In [6]:
# Passing boolean array gives the records with the True label

a[np.logical_or(a==19,a==22)]

array([19, 22, 22, 22])

##### another way of approach to find/extract the elements 19 and 22 in an numpy array

In [7]:
a==19

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [8]:
a==22

array([False, False, False, False,  True,  True, False, False, False,
       False,  True])

In [9]:
(a==19) | (a==22)

array([ True, False, False, False,  True,  True, False, False, False,
       False,  True])

In [10]:
a[(a==19) | (a==22)]

array([19, 22, 22, 22])

##### to find indices of the numbers 19 & 22 in an numpy array

In [15]:
np.where((a==19) | (a==22))

(array([ 0,  4,  5, 10], dtype=int64),)

##### another way to find indices of the numbers 19 & 22 in an numpy array

In [16]:
np.where(np.logical_or((a==19),(a==22)))

(array([ 0,  4,  5, 10], dtype=int64),)

### 2D array

In [36]:
np.random.seed(28)

a = np.random.randint(16,36,(3,3))
a

array([[17, 21, 16],
       [19, 28, 16],
       [35, 28, 28]])

##### find/extract the elements 17 and 28 in an numpy 2D array

In [38]:
a==17, a==28

(array([[ True, False, False],
        [False, False, False],
        [False, False, False]]),
 array([[False, False, False],
        [False,  True, False],
        [False,  True,  True]]))

In [41]:
(a==17) | (a==28)

array([[ True, False, False],
       [False,  True, False],
       [False,  True,  True]])

In [40]:
a[(a==17) | (a==28)]

array([17, 28, 28, 28])

##### another way of approach to find/extract the elements 17 and 28 in an numpy 2D array

In [42]:
np.logical_or(a==17,a==28)

array([[ True, False, False],
       [False,  True, False],
       [False,  True,  True]])

In [43]:
a[np.logical_or(a==17,a==28)]

array([17, 28, 28, 28])

##### to find indices of the numbers 17 & 28 in an numpy array

In [46]:
np.where((a==17) | (a==28))

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 1, 2], dtype=int64))

##### another way to find indices of the numbers 17 & 28 in an numpy array

In [45]:
np.where(np.logical_or((a==17),(a==28)))

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 1, 2], dtype=int64))