In [27]:
import numpy as np
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('E:/Python Programs/titanic.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [4]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [5]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

## Step-1 Train-Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'],test_size=0.2,random_state=42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((334, 7), (334,), (84, 7), (84,))

In [7]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     2
dtype: int64

## Applying imputation

In [8]:
si_age = SimpleImputer()
si_fare = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_fare = si_fare.fit_transform(X_train[['Fare']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.fit_transform(X_test[['Age']])
X_test_fare = si_fare.fit_transform(X_test[['Fare']])
X_test_embarked = si_embarked.fit_transform(X_test[['Embarked']])

In [9]:
X_train_age

array([[32.        ],
       [24.        ],
       [30.11576336],
       [24.        ],
       [19.        ],
       [30.11576336],
       [25.        ],
       [ 6.        ],
       [46.        ],
       [14.        ],
       [25.        ],
       [10.        ],
       [31.        ],
       [17.        ],
       [30.11576336],
       [35.        ],
       [24.        ],
       [30.11576336],
       [23.        ],
       [27.        ],
       [27.        ],
       [30.11576336],
       [17.        ],
       [23.        ],
       [30.11576336],
       [22.        ],
       [30.11576336],
       [61.        ],
       [11.5       ],
       [30.11576336],
       [ 6.        ],
       [30.11576336],
       [22.        ],
       [26.        ],
       [ 0.92      ],
       [22.        ],
       [30.11576336],
       [27.        ],
       [18.        ],
       [30.11576336],
       [33.        ],
       [23.        ],
       [36.        ],
       [30.11576336],
       [63.        ],
       [22

## One Hot Encoding on Sex & Embarked in X_features

In [10]:
ohe_sex = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse=False, handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [11]:
X_train.head(2)

Pclass   Sex   Age  SibSp  Parch  Fare Embarked
336       2  male  32.0      0      0  13.0        S
31        2  male  24.0      2      0  31.5        S

In [12]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [13]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [14]:
X_train_rem = X_train.drop(columns=['Sex','Age','Fare','Embarked'])

In [15]:
X_test_rem = X_test.drop(columns=['Sex','Age','Fare','Embarked'])

In [16]:
X_train_rem.head(2)

Pclass  SibSp  Parch
336       2      0      0
31        2      2      0

In [17]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_fare,X_train_sex,X_train_embarked),axis=1)

In [18]:
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_fare,X_test_sex,X_test_embarked),axis=1)

In [19]:
len(X_test_sex)

84

In [30]:
X_train_transformed.shape

(334, 10)

In [20]:
X_train_transformed

array([[2., 0., 0., ..., 0., 0., 1.],
       [2., 2., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 1., 0.]])

In [21]:
X_test_transformed

array([[3.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.50000000e+01,
        7.22920000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.90000000e+01,
        2.11337500e+02, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.10000000e+01,
        7.75000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        7.89580000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 2.00000000e+00, 3.60000000e+01,
        1.21833000e+01, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
   

In [22]:
dt = DecisionTreeClassifier()
dt.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [23]:
y_pred = dt.predict(X_test_transformed)
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [26]:
accuracy_score(y_test, y_pred)

1.0

## Exporting the model

In [29]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(dt,open('models/dt.pkl','wb'))